'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
let selected=localStorage.getItem('mn-session'), sessions=[], data=null, paused=false, tab='trades', page=0, busy=false, rendered=null;
const PAGE=12;
function text(id,value){$(id).textContent=value??'—'}
function fmt(v,d=2){return v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d})}
function pnl(v){return fmt(v,data?.lot?6:2)}
function duration(ms){if(ms==null)return '—';let s=Math.floor(ms/1000);return `${Math.floor(s/3600).toString().padStart(2,'0')}:${Math.floor(s/60)%60<10?'0':''}${Math.floor(s/60)%60}:${(s%60).toString().padStart(2,'0')}.${Math.floor(ms%1000).toString().padStart(3,'0')}`}
function quantity(v){return v==null?'—':data?.lot?fmt(v*data.lot,Math.min(8,Math.max(0,Math.ceil(-Math.log10(data.lot))))):fmt(v,0)}
function price(v){return v==null?'—':data?.tick?fmt(v*data.tick,Math.min(8,Math.max(0,Math.ceil(-Math.log10(data.tick))))):fmt(v,0)}
function polarity(id,n){$(id).classList.toggle('positive',n>0);$(id).classList.toggle('negative',n<0)}
function mode(m){return ({'testnet':'Spot testnet','testnet-churn':'Testnet churn','adversarial-paper':'Latency experiment','paper':'Paper','journal':'Journal replay'})[m]||m}
function renderSessions(){let search=$('session-search').value.toLowerCase();$('sessions').replaceChildren();text('session-count',sessions.length);for(const s of sessions.filter(s=>s.name.toLowerCase().includes(search))){let b=document.createElement('button');b.type='button';b.className='session'+(s.id===selected?' active':'');b.setAttribute('aria-pressed',s.id===selected);let name=document.createElement('strong');name.textContent=s.name.replace(/\/events\.jsonl$/,'');let meta=document.createElement('small'),label=document.createElement('span'),state=document.createElement('span');label.textContent=mode(s.mode||'journal');state.textContent=s.error?'Error':s.health||'Loading';meta.append(label,state);b.append(name,meta);b.onclick=()=>{selected=s.id;paused=false;text('pause','Pause view');localStorage.setItem('mn-session',selected);page=0;data=null;renderSessions();poll()};$('sessions').append(b)}}
function svg(tag,attrs,content){let e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(content!=null)e.textContent=content;return e}
function drawChart(){let root=$('chart');root.replaceChildren();let points=data.history||[];if(!points.length)return;let left=66,right=870,start=points[0].at,end=points.at(-1).at;const x=t=>left+(t-start)/Math.max(end-start,1)*(right-left);let values=points.map(p=>p.pnl).filter(v=>v!=null),lo=Math.min(0,...values),hi=Math.max(0,...values);if(lo===hi){hi=lo+1;lo-=1}let padding=(hi-lo)*.12;lo-=padding;hi+=padding;const y=n=>155-(n-lo)/(hi-lo)*125;
for(let i=0;i<4;i++){let value=lo+(hi-lo)*i/3,yy=y(value);root.append(svg('line',{x1:left,x2:right,y1:yy,y2:yy,stroke:'#e5ebf2','stroke-width':1}),svg('text',{x:left-10,y:yy+3,'text-anchor':'end',fill:'#8a9bac','font-size':10},fmt(value,Math.abs(value)<1?4:Math.abs(value)<10?2:0)))}
let segments=[],part=[];for(const p of points){if(p.pnl==null){if(part.length)segments.push(part);part=[]}else part.push(p)}if(part.length)segments.push(part);for(const seg of segments){let line=seg.map((p,i)=>`${i?'L':'M'}${x(p.at)},${y(p.pnl)}`).join(' ');root.append(svg('path',{d:line+` L${x(seg.at(-1).at)},155 L${x(seg[0].at)},155 Z`,fill:'#187e8b0e'}),svg('path',{d:line,fill:'none',stroke:'#187e8b','stroke-width':2.2,'stroke-linejoin':'round'}))}
root.append(svg('text',{x:left,y:190,fill:'#72869b','font-size':10},'Position / target (lots)'));
let min=Math.min(0,...points.flatMap(p=>[p.position,p.target??p.position])),max=Math.max(1,...points.flatMap(p=>[p.position,p.target??p.position]));const yp=n=>249-(n-min)/Math.max(1,max-min)*44;root.append(svg('line',{x1:left,x2:right,y1:249,y2:249,stroke:'#e5ebf2'}));for(const value of [min,max])root.append(svg('text',{x:left-10,y:yp(value)+3,'text-anchor':'end',fill:'#8a9bac','font-size':10},fmt(value,0)));for(const [key,color,dashed]of [['position','#5d7aa5',false],['target','#7565ac',true]]){let d='',last=null;for(const p of points){let v=p[key];if(v==null){last=null;continue}d+=last==null?` M${x(p.at)},${yp(v)}`:` H${x(p.at)} V${yp(v)}`;last=v}root.append(svg('path',{d,fill:'none',stroke:color,'stroke-width':2,'stroke-dasharray':dashed?'5 4':'none'}))}
for(let i=0;i<5;i++){let t=start+(end-start)*i/4;root.append(svg('text',{x:x(t),y:277,'text-anchor':'middle',fill:'#8a9bac','font-size':10},duration(t).slice(0,8)))}let cursor=svg('line',{x1:left,x2:left,y1:18,y2:253,stroke:'#93aabc','stroke-dasharray':'3 3',visibility:'hidden'});root.append(cursor);root.onpointermove=e=>{let box=root.getBoundingClientRect(),px=(e.clientX-box.left)*900/box.width,t=start+(px-left)/(right-left)*(end-start),p=points.reduce((a,b)=>Math.abs(a.at-t)<Math.abs(b.at-t)?a:b);cursor.setAttribute('x1',x(p.at));cursor.setAttribute('x2',x(p.at));cursor.setAttribute('visibility','visible');$('chart-tooltip').hidden=false;$('chart-tooltip').textContent=`${duration(p.at)}\nGross PnL  ${pnl(p.pnl)} ${data.unit}\nPosition  ${p.position} lots   Target  ${p.target??'—'}`};root.onpointerleave=()=>{cursor.setAttribute('visibility','hidden');$('chart-tooltip').hidden=true};text('chart-range',`${duration(start)} — ${duration(end)}`);text('chart-note',`${points.length.toLocaleString()} samples · full span, downsampled`)}
function eventName(event){return typeof event==='string'?event:Object.keys(event||{})[0]||'—'}
function describe(event){if(typeof event==='string')return '';let name=eventName(event),p=event[name];if(name==='SubmitTargeted')p=p.intent;if(name==='Submit'||name==='SubmitTargeted')return `${p.side} ${quantity(p.qty)} @ ${price(p.limit)} · order ${p.id}`;if(name==='Execution')return `${eventName(p.report)} · ${JSON.stringify(p.report[eventName(p.report)])}`;if(name==='SetTarget')return `Target ${quantity(p.position)} · revision ${p.revision}`;return JSON.stringify(p)}
function rows(){return (data?.[tab]||[]).filter(r=>{let side=r.side||JSON.stringify(r.event||'').match(/"side":"(Buy|Sell)"/)?.[1];return ($('side').value==='all'||side===$('side').value)&&JSON.stringify(r).toLowerCase().includes($('activity-search').value.toLowerCase())})}
function cell(value,className=''){let td=document.createElement('td');td.textContent=value??'—';td.className=className;return td}
function sideCell(side){let td=document.createElement('td'),span=document.createElement('span');span.className='side '+(side==='Buy'?'buy':'sell');span.textContent=side;td.append(span);return td}
function renderTable(){if(!data)return;let all=rows();page=Math.max(0,Math.min(page,Math.ceil(all.length/PAGE)-1));let headers=tab==='trades'?['Observed time','Execution / order','Side','Quantity','Price','Fee']:tab==='orders'?['Order','Side','Quantity / filled','Limit price','State','Pending']:tab==='signals'?['Engine time','Sequence','Target / revision','Result']:['Engine time','Sequence','Action','Detail / outcome'];$('table-head').replaceChildren();let hr=document.createElement('tr');headers.forEach(h=>hr.append(cell(h)));for(const c of [...hr.children]){let th=document.createElement('th');th.textContent=c.textContent;c.replaceWith(th)}$('table-head').append(hr);$('table-body').replaceChildren();for(const r of all.slice(page*PAGE,(page+1)*PAGE)){let tr=document.createElement('tr');if(tab==='trades')tr.append(cell(duration(r.at)),cell(`${r.id} / ${r.order_id}`),sideCell(r.side),cell(quantity(r.qty),'numeric'),cell(price(r.price),'numeric'),cell(r.fee?`${r.fee.amount} ${r.fee.asset}`:'Not recorded','status'));else if(tab==='orders')tr.append(cell(r.id),sideCell(r.side),cell(`${quantity(r.qty)} / ${quantity(r.filled)}`,'numeric'),cell(price(r.price),'numeric'),cell(r.status+(r.uncertain?' · uncertain':''),'status'),cell(r.pending||'—','status'));else if(tab==='signals')tr.append(cell(duration(r.at)),cell(r.seq),cell(describe(r.event)),cell(r.accepted?'Accepted':'Refused',r.accepted?'positive':'negative'));else{let detail=describe(r.event);if(r.effects?.length)detail+='  '+r.effects.map(e=>`${eventName(e)}: ${typeof e==='string'?'':JSON.stringify(e[eventName(e)])}`).join(' / ');tr.append(cell(duration(r.at)),cell(r.seq),cell(eventName(r.event)),cell(detail,'reason'))}$('table-body').append(tr)}if(!all.length){let tr=document.createElement('tr'),td=cell('No matching records yet.','no-rows');td.colSpan=headers.length;tr.append(td);$('table-body').append(tr)}text('row-status',`${all.length?`${page*PAGE+1}–${Math.min((page+1)*PAGE,all.length)} of ${all.length.toLocaleString()}`:'0 records'} · newest first`);text('page-label',`${page+1} / ${Math.max(1,Math.ceil(all.length/PAGE))}`);$('prev').disabled=page===0;$('next').disabled=(page+1)*PAGE>=all.length}
function render(){if(!data)return;$('empty').hidden=!!data.ready;$('workspace').hidden=!data.ready;text('run-title',data.name?.replace(/\/events\.jsonl$/,'')||'Loading journal');text('symbol',data.symbol);text('mode',mode(data.mode||'journal'));text('sequence',`Sequence ${data.seq||'0'}`);$('notice').hidden=!data.error;$('notice').textContent=data.error?`Observer stopped: ${data.error}. Values below are the last validated state.`:'';if(!data.ready)return;let p=data.pnl;text('gross',pnl(p.gross));polarity('gross',p.gross);text('realized',pnl(p.realized));text('unrealized',pnl(p.unrealized));polarity('realized',p.realized);polarity('unrealized',p.unrealized);text('position',quantity(data.position));text('target',quantity(data.target?.position));text('position-bounds',`· bounds ${quantity(Number(data.lower))} / ${quantity(Number(data.upper))}`);text('qty-unit',data.lot?'base units':'lots');text('unit',data.unit);text('fills',fmt(data.fill_count,0));text('trade-tab-count',fmt(data.fill_count,0));text('open-orders',data.open_orders);text('total-orders',data.order_count);text('health',data.killed?'Kill latched':data.health);$('health-dot').classList.toggle('offline',data.health!=='Healthy'||data.killed);text('engine-time',duration(data.engine_time));text('refusals',data.refusals);text('recoveries',data.recoveries);text('fees',p.fees==null?'—':`${fmt(p.fees,6)} ${data.unit}`);text('net',pnl(p.net));text('fee-note',p.fees==null?'Net PnL unavailable until complete fee records are available.':'Complete audited fees; base fees converted at execution price.');text('mark-basis',data.position===0?'Gross cash from fills':data.mark_stale?'Last known mark · stale':'Marked at executable side');text('mark-detail',data.mark==null?'No market mark recorded':`${data.position<0?'Ask':'Bid'} ${price(data.mark)} · observed ${duration(data.mark_at)}${data.mark_stale?' · stale':''}`);text('last-update',`Journal observed ${data.updated_at?new Date(Number(data.updated_at)).toLocaleTimeString():'—'}`);text('observer',paused?'View paused':data.error?'Stopped':data.catching_up?'Replaying journal':data.pending_tail?'Waiting for frame':Date.now()-Number(data.updated_at)<3000?'Receiving updates':'No new events');let signature=JSON.stringify([data.id,data.seq,data.tick,data.lot,data.pnl.fees]);if(signature!==rendered){drawChart();renderTable();rendered=signature}}
async function poll(){if(busy||paused)return;busy=true;try{let response=await fetch('/api/sessions');if(!response.ok)throw Error('Observer unavailable');let payload=await response.json();sessions=payload.sessions.sort((a,b)=>Number(b.modified_at)-Number(a.modified_at));if(!sessions.some(s=>s.id===selected))selected=sessions[0]?.id;renderSessions();if(selected){let requested=selected;let r=await fetch(`/api/session/${requested}`);if(!r.ok)throw Error('Session unavailable');let next=await r.json();if(requested===selected&&!paused){data=next;render()}}text('connection','Observer connected');$('connection-dot').classList.remove('offline')}catch(e){text('connection','Observer disconnected');$('connection-dot').classList.add('offline');$('notice').hidden=false;$('notice').textContent='Connection lost. Displayed values are frozen until the observer reconnects.'}finally{busy=false}}
$('pause').onclick=()=>{paused=!paused;text('pause',paused?'Resume view':'Pause view');text('observer',paused?'View paused':'Receiving updates');if(!paused)poll()};$('session-search').oninput=renderSessions;for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;page=0;document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',x===b));renderTable()};$('activity-search').oninput=$('side').onchange=()=>{page=0;renderTable()};$('prev').onclick=()=>{page--;renderTable()};$('next').onclick=()=>{page++;renderTable()};$('export').onclick=()=>{if(!data)return;const escape=v=>`"${String(v??'').replaceAll('"','""')}"`;let csv=[['execution_id','order_id','side','quantity_lots','price_ticks','observed_engine_ms','fee','fee_asset'],...(data.trades||[]).map(r=>[r.id,r.order_id,r.side,r.qty,r.price,r.at,r.fee?.amount,r.fee?.asset])].map(row=>row.map(escape).join(',')).join('\n');let url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='mininautilus-trades.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)};poll();setInterval(poll,500);
